Make consistent order of hands up
mattermost/mattermost-plugin-calls pull request #215
Opened 2022-09-30 15:00 UTC by cyrilzhang-mm

#### Summary

Create the hands up array in the same order as the participants list RHS, so hands up are shown in the order that they were raised. Also changed the background colour to white. 

<img width="1512" alt="Screen Shot 2022-09-30 at 10 57 24 AM" src="https://user-images.githubusercontent.com/112951043/193298717-86d4fe6f-6f07-400d-b6bf-84f9b5f0d92c.png">

2022-09-30 15:07 UTC, Willyfrog requested changes
This is having the same problem as before as it is using the object keys in whatever ordering is handled, so it might work sometimes but can't be trusted. We need to sort by the value of hands up as I believe it is a timestamp

2022-09-30 15:23 UTC, cyrilzhang-mm commented
@Willyfrog I think it's okay because it's using the `profiles` prop, which is an array so it is ordered, and the participants list is ordered in the same way using the `profiles` prop
https://github.com/mattermost/mattermost-plugin-calls/blob/e617565854023842049ee6a27f1ba8e84658bfbc/webapp/src/components/expanded_view/component.tsx#L488-L497
the `profiles` prop is sorted before being passed into the component
https://github.com/mattermost/mattermost-plugin-calls/blob/e617565854023842049ee6a27f1ba8e84658bfbc/webapp/src/components/expanded_view/index.ts#L23-L28

2022-09-30 17:10 UTC, Willyfrog commented
> the `profiles` prop is sorted before being passed into the component
> 

Oh, that's right! Never mind my comment then

2022-09-30 17:10 UTC, Willyfrog approved these changes

2022-10-04 08:37 UTC, AGMETEOR approved these changes
LGTM

2022-10-04 13:10 UTC, merged