MM-54743 - Fix: In compact mode, the call card displays inline
mattermost/mattermost-plugin-calls pull request #571
Opened 2023-11-22 23:40 UTC by cpoile

#### Summary
- Had to do some trickery to force the display to wrap (because we don't control our custom post's container).
- Doesn't affect non-compact mode, or when a call title is present. If you can think of any other situations I didn't think, please let me know.

| compact, full width | compact, reduced width |
|--|--|
| <img width="1006" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/46ac1efc-cf12-4b39-bae2-73f2674eddc8"> | <img width="544" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/c11090b2-3fb1-4106-ad52-f7d8ccbeb84c"> |

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-54743

2023-11-23 01:18 UTC, streamer45 approved these changes

2023-11-23 01:18 UTC, streamer45 commented on webapp/src/components/custom_post_types/post_type/component.tsx
> +    const compactTitle = compactDisplay ? '\u200b' : '';
Any reason for not using something more semantically defined like the `<br>` tag?

2023-11-23 20:03 UTC, matthewbirtch requested changes
@cpoile this looks good, but I did notice an issue in the RHS in compact mode. There seems to be extra space added that is not there in standard display mode:

**Compact display mode**
Notice the extra space between the username and the call card
<img width="502" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/2040554/02578d7a-4b7c-4e71-8d6b-46b10b5e297c">

**Standard display mode**
<img width="513" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/2040554/0e7134c6-1fac-4a17-8d47-7d09554e93b6">

Other than that, this should be good.

2023-11-23 23:10 UTC, cpoile commented
Fixed now, thanks for pointing that out Matt!

2023-11-24 13:43 UTC, matthewbirtch approved these changes
Looks good. Thanks Chris!

2023-11-24 13:44 UTC, merged