[MM-58284] Confirmation when leaving a call
mattermost/mattermost-plugin-calls pull request #763
Opened 2024-06-04 21:03 UTC by cpoile

#### Summary
- Added confirmations on the widget, global widget, expanded view, and post component's leave call buttons
- The global widget required an added shim to give room for the confirmation, please see if it works well on linux desktop :)
- The popup system needed a bit of reworking to add the tooltips, kind of a mess, but I think I figured out how to do it in an elegant way that doesn't affect the existing uses (host controls), but would appreciate a second pair of eyes on that just in call (that the tooltips look correct in all places on the leave button, and that the host controls still work/look as expected).

First row is from desktop and host, second row is from participant and webapp:

| | | |
|--|--|--|
| <img width="431" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/77f9de8a-0a4d-431f-8a25-c3cfaf1ebfa0"> | <img width="847" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/5e7097ce-6946-4ba8-997b-db20260b0b15"> | <img width="641" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/261644c2-63ad-41cf-9135-0366ba12d068"> |
| <img width="573" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/67c2e400-dc4a-4f30-9dc1-fb5251e25fea"> | <img width="656" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/ebe14998-2e6c-4886-9c9c-e082dcbc1a47"> | <img width="527" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/1490756/a4a8c160-7d17-49b7-ba6e-d3f97b8dcf48"> | 

- Designs: https://www.figma.com/design/sECejPEfl6OjuJxj0WU9sb/MM-58284-Leaving-and-Ending-a-Call?node-id=1-7&m=dev

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-58284

2024-06-06 09:03 UTC, streamer45 reviewed
Looks great, even on :penguin: :)

Two things I noticed:

- The keyboard shortcut causes the user to leave immediately. This is fine but inconsistent with how we are handling a similar case in https://github.com/mattermost/mattermost-plugin-calls/pull/760.
- Ending the call is not working as I'd expect, although this is unrelated to this PR. The call post should update immediately but for some reason, that's not happening until the server timeout triggers. We should look into this.

2024-06-06 13:39 UTC, cpoile commented on webapp/src/components/expanded_view/component.tsx
> ->>>>>>> origin/main
I don't know how that got there and how it survived.

2024-06-06 13:46 UTC, cpoile commented
@streamer45 for 1: Earlier I had messaged @abhijit-singh about it too. I suggested we keep the shortcut as it has been, under the assumption that if you hit it that means you want it to happen right then, not that you then want to use the mouse and click again. Your right that it doesn't match the end recording, but in that case the action is more destructive, whereas you can always rejoin if you left by accident. Imo, it just seems annoying that the shortcut just opens a little popup. If we made it do that, I would vote we just remove the shortcut altogether for uselessness. :)

For 2, I can look into that. I think it's been happening like that for a long time.

2024-06-06 14:44 UTC, streamer45 commented
> @streamer45 for 1: Earlier I had messaged @abhijit-singh about it too. I suggested we keep the shortcut as it has been, under the assumption that if you hit it that means you want it to happen right then, not that you then want to use the mouse and click again. Your right that it doesn't match the end recording, but in that case the action is more destructive, whereas you can always rejoin if you left by accident. Imo, it just seems annoying that the shortcut just opens a little popup. If we made it do that, I would vote we just remove the shortcut altogether for uselessness. :)

Yeah, I agree. Shortcut to show a popup is weird.

> For 2, I can look into that. I think it's been happening like that for a long time.

Thanks.

2024-06-06 14:45 UTC, streamer45 approved these changes
Great! And thanks for the brave effort on e2e and related lint checks.

2024-06-06 15:12 UTC, cpoile commented
@streamer45 Fixed how we were doing call end, and exposing the `end call for everyone` button to admins.

2024-06-06 15:27 UTC, streamer45 approved these changes
Working great now!

2024-06-06 21:57 UTC, cpoile commented
fyi: added a rule to only show `End call for everyone` when there are other people in the call.

2024-06-10 19:31 UTC, abhijit-singh requested changes
Thanks @cpoile! Looks good! I have a few requests - 
1. In the expanded window, can we align the right edge of the confirmation pop-out with the right edge of the button?
2. Also in the expanded window, can we make the border radius for the pop-out 8px to match that of the button?

Current: 
<img width="222" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/14369607/1364e103-cc7e-4d93-bf37-90f1f532a293">

Ideal:
<img width="199" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/14369607/11ad0216-df38-4238-b937-f97dbc2c36f5">

Note that the above two requests apply to the popout window only. 
3. Can we increase the width of the menu items to 36px to be consistent with the rest of the app? Right now it seems to be 32px. 

Current:
<img width="328" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/14369607/728171ae-b8f9-4b93-8487-6ecb92a9f11f">

4. On the Desktop App, in the floating widget, clicking outside the popout menu (within the widget boundries, does not close the popout menu. Ideally it should close when clicked outside.

2024-06-11 17:17 UTC, cpoile commented
@abhijit-singh 1-3 done, thanks! 4 took me awhile, but I don't think we can solve it. The problem is that when you click on another part of the widget that is meant to be draggable, the click doesn't register (but you can drag). If you click on any place you can click, the menu will close (e.g. on a participant in the participant list, or any of the widget buttons). So unfortunately I think we're stuck with that -- the user will have to click on the `Cancel` button if they change their mind (or click on a participant or settings menu item).

2024-06-12 13:48 UTC, abhijit-singh approved these changes
Looks good to me, thanks @cpoile!

2024-06-12 14:04 UTC, merged